use agent container volumes in sub containers

diff --git a/agent/tools/run b/agent/tools/run
--- a/agent/tools/run
+++ b/agent/tools/run
@@ -10,8 +10,22 @@ DOCKER_IMAGE=$1
 [ -z "$DOCKER_IMAGE" ] && usage_exit
 shift
 
+# find the real agent container
+DOCKER_AGENT_CONTAINER=
+for contid in $(docker ps -q); do
+    if [ ! -z "$(docker inspect $contid | grep '/var/lib/go-agent')" ]; then
+        DOCKER_AGENT_CONTAINER=$contid
+        break
+    fi
+done
+if [ -z "$DOCKER_AGENT_CONTAINER" ]; then
+    echo "Could not find go-agent conainer!" >&2
+    exit 1
+fi
+
 # default Docker options to provide necessary directories
-DOCKER_OPTS="--rm -e USER_ID=$(id -u) -e HOME=$HOME -v $HOME:$HOME -v /tools:/tools -v $(pwd):/work"
+# https://docs.docker.com/engine/userguide/dockervolumes/#creating-and-mounting-a-data-volume-container
+DOCKER_OPTS="--rm -e USER_ID=$(id -u) -e HOME=$HOME --volumes-from $DOCKER_AGENT_CONTAINER -w $(pwd)"
 
 PRINT_ONLY=false
 
